POST http://localhost:80/api/auth/signup
Content-Type: application/json

{
    "id": "vladtest",
    "email": "vladtest@er.com",
    "name": "vladtest",
    "password": "vladtest"
}

###

POST http://localhost:80/api/auth/login
Content-Type: application/json

{
    "email": "vladtest@er.com",
    "password": "vladtest"
}

###

GET http://localhost:80/api/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU4NTk3NTI2LCJleHAiOjE2NTg2MDExMjYsIm5iZiI6MTY1ODU5NzUyNiwianRpIjoiMUFpS2w5V0dJZHZWRVVCdSIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.CZXx8vrXdmiIo_h_Dggf5GKSwqlgkcrIoaRBqFsEhys
Content-Type: application/json

###

GET http://localhost:80/api/auth/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU4NTk3NTI2LCJleHAiOjE2NTg2MDExMjYsIm5iZiI6MTY1ODU5NzUyNiwianRpIjoiMUFpS2w5V0dJZHZWRVVCdSIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.CZXx8vrXdmiIo_h_Dggf5GKSwqlgkcrIoaRBqFsEhys
Content-Type: application/json

###

GET http://localhost:80/api/auth/user-profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU4NTk3NTI2LCJleHAiOjE2NTg2MDExMjYsIm5iZiI6MTY1ODU5NzUyNiwianRpIjoiMUFpS2w5V0dJZHZWRVVCdSIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.CZXx8vrXdmiIo_h_Dggf5GKSwqlgkcrIoaRBqFsEhys
Content-Type: application/json

###

POST http://localhost:80/api/car/create
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU4NTk3NTI2LCJleHAiOjE2NTg2MDExMjYsIm5iZiI6MTY1ODU5NzUyNiwianRpIjoiMUFpS2w5V0dJZHZWRVVCdSIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.CZXx8vrXdmiIo_h_Dggf5GKSwqlgkcrIoaRBqFsEhys
Content-Type: application/json

{
    "manufacturer_id": "10",
    "model_id": "3",
    "body_id": "2",
    "engine_id": "2",
    "transmission_id": "1",
    "mileage": "111",
    "headlight": "test",
    "taillight": "test",
    "marriage": "test",
    "notes": "test",
    "notes_zibiz": "test",
    "images": "test",
    "videos": "test",
    "user_id": "3",
    "body_no": "test",
    "engine_no": "test",
    "in_the_way": 2,
    "retail": 2,
    "small": 2,
    "archive": 2,
    "sticker_notes": "test11111@er.com",
    "manager_id": 2,
    "documents": "test",
    "provider_id": "4",
    "provider_engine_price": "1236"
}

###

POST http://localhost:80/api/car/update/8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU4NTk3NTI2LCJleHAiOjE2NTg2MDExMjYsIm5iZiI6MTY1ODU5NzUyNiwianRpIjoiMUFpS2w5V0dJZHZWRVVCdSIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.CZXx8vrXdmiIo_h_Dggf5GKSwqlgkcrIoaRBqFsEhys
Content-Type: application/json

{
    "taillight": "no",
    "marriage": "no",
    "notes": "no",
    "notes_zibiz": "no",
    "images": "no",
    "videos": "no",
    "user_id": "3",
    "body_no": "no",
    "engine_no": "no",
    "in_the_way": 3,
    "retail": 3,
    "small": 3,
    "archive": 3,
    "sticker_notes": "tet@er.com",
    "manager_id": 3,
    "documents": "1238ewerww567",
    "provider_id": "3",
    "provider_engine_price": "1235"
}

###

GET http://localhost:80/api/car/delete/8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU4NTk3NTI2LCJleHAiOjE2NTg2MDExMjYsIm5iZiI6MTY1ODU5NzUyNiwianRpIjoiMUFpS2w5V0dJZHZWRVVCdSIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.CZXx8vrXdmiIo_h_Dggf5GKSwqlgkcrIoaRBqFsEhys
Content-Type: application/json

###

GET http://localhost:80/api/car/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

###

GET http://localhost:80/api/car/show/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

###

POST http://localhost:80/api/provider/create
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

{
    "name": "NAKATA",
    "email": "nakata@mail.ru",
    "percent": 10
}


###

POST http://localhost:80/api/provider/update/5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

{
    "name": "NAKATA",
    "email": "nakata@mail.ru",
    "percent": 10
}

###

GET http://localhost:80/api/provider/delete/4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

###

GET http://localhost:80/api/provider/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

###

GET http://localhost:80/api/provider/show/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzg4NjAyLCJleHAiOjE2NTk3OTIyMDIsIm5iZiI6MTY1OTc4ODYwMiwianRpIjoidHo1UkR2SEd6bXFudWpBMyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.49rTgZZ5muF9RvbyyxfGmQttUjhBqRelHhwvk8P_aNY
Content-Type: application/json

###

POST http://localhost:80/api/part/create
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzk3MjY3LCJleHAiOjE2NTk4MDA4NjcsIm5iZiI6MTY1OTc5NzI2NywianRpIjoiMlRrT0ZQbU9Mc1J2b0hFSyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.cDvBlECZzZCABDdxQWmbCFvgS4n1p8KbGsRbjBD_EiU
Content-Type: application/json

{
    "name_ru": "Тест2",
    "name_en": "Test2",
    "sticker_fields": "test text2",
    "sort": 4
}
###

POST http://localhost:80/api/part/update/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzk3MjY3LCJleHAiOjE2NTk4MDA4NjcsIm5iZiI6MTY1OTc5NzI2NywianRpIjoiMlRrT0ZQbU9Mc1J2b0hFSyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.cDvBlECZzZCABDdxQWmbCFvgS4n1p8KbGsRbjBD_EiU
Content-Type: application/json

{
    "name_ru": "Тест",
    "name_en": "Test",
    "sticker_fields": "text test",
    "sort": 2
}

###

GET http://localhost:80/api/part/delete/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzk3MjY3LCJleHAiOjE2NTk4MDA4NjcsIm5iZiI6MTY1OTc5NzI2NywianRpIjoiMlRrT0ZQbU9Mc1J2b0hFSyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.cDvBlECZzZCABDdxQWmbCFvgS4n1p8KbGsRbjBD_EiU
Content-Type: application/json

###

GET http://localhost:80/api/part/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzk3MjY3LCJleHAiOjE2NTk4MDA4NjcsIm5iZiI6MTY1OTc5NzI2NywianRpIjoiMlRrT0ZQbU9Mc1J2b0hFSyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.cDvBlECZzZCABDdxQWmbCFvgS4n1p8KbGsRbjBD_EiU
Content-Type: application/json

###

GET http://localhost:80/api/part/show/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU5Nzk3MjY3LCJleHAiOjE2NTk4MDA4NjcsIm5iZiI6MTY1OTc5NzI2NywianRpIjoiMlRrT0ZQbU9Mc1J2b0hFSyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.cDvBlECZzZCABDdxQWmbCFvgS4n1p8KbGsRbjBD_EiU
Content-Type: application/json
